site_name: Offensive Graphs Playground
site_url: https://offensivegraphs.ai
repo_url: https://github.com/andreashappe/offensivegraphs
theme:
  name: material
  features:
    - content.code.annotation
    - content.code.copy
    - navigation.expand
    - navigation.instant.preview
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal   
plugins:
  - blog
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  analytics:
    provider: google
    property: G-XVEVXNXJ44
