authors:
  andreashappe:
    name: Andreas Happe
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/20667?v=4
    url: https://github.com/andreashappe
  brandl:
    name: Jürgen Brandl
    description: Co-Creator
    avatar: https://avatars.githubusercontent.com/u/3877188?v=4
    url: https://github.com/brandl
